### PR TITLE
Published online

### PR DESCRIPTION
**Pull request by jesusbagpuss**
Hi @wfyson,
As discussed - a few updates / tweaks.

I've added you to the list of authors in the epmi, but I haven't built an epm from it yet.

Can you check these changes are sane?

### CODE REVIEW

**Comment by jesusbagpuss** [comment]
Fixes #7

**Comment by wfyson** [comment]
All looks good to me, shall I leave it to you to update the Bazaar plugin? Thanks for looking into this!

**Comment by jesusbagpuss** [comment]
@wfyson - I've packaged it from the command line on a test server - but when it does this, it doesn't set the mime_types for the files. I'm not sure if this is an issue or not.
I'll try and get a vanilla repository to upload/test the package on before adding it to the bazaar (if you've got access to an install that you could check the epm on, got for it - let me know if it's OK!).

**Comment by jesusbagpuss** [comment]
I've tested it on a 3.3.12 archive - seems to be OK now (having fixed the missing comma).

**Comment by wfyson** [comment]
Excellent, thanks for testing. What's the situation with regards to rolling it out to the bazaar - shall I go ahead and do that?

**Comment by jesusbagpuss** [comment]
@wfyson 
If you've tested it too, and are happy with it, I'd appreciate you adding it to the Bazaar.
I'm going to take a look into the HEFCE plugin now - there's a few things there that I need to do!

**Comment by wfyson** [comment]
Not a problem, I'll do it as soon as possible (although that will probably be next week sometime!). Thanks!

**Comment by wfyson** [comment]
Just to let you know this has been added to the bazaar now (after a couple of bazaar related mishaps!)

**Pull request merged**
